import type { StrategyConfig } from "@/types";

export type AssetClass = "penny" | "largecap" | "forex";
export type Difficulty = "מתחיל" | "מתקדם" | "מקצועי";

export interface LibraryStrategy {
  id: string;
  name: string;
  nameEn: string;
  assetClass: AssetClass;
  difficulty: Difficulty;
  description: string;
  logic: string;                 // plain-language explanation
  winRate: number;               // typical historical %
  profitFactor: number;
  typicalTp: number;             // %
  typicalSl: number;             // %
  timeframe: "1m" | "5m" | "15m" | "1D";
  avgHoldMinutes: number;
  sources: string;               // where the strategy comes from
  tags: string[];
  config: StrategyConfig;
}

export const LIBRARY: LibraryStrategy[] = [
  // ─── PENNY STOCKS ────────────────────────────────────────────────────────────
  {
    id: "gap-and-go",
    name: "Gap & Go — פריצת פער פתיחה",
    nameEn: "Gap and Go",
    assetClass: "penny",
    difficulty: "מתחיל",
    description: "מניית פני עם פתיחה גבוהה ב-15%+ לעומת הסגירה הקודמת, פלוואט נמוך ונפח ראשוני גבוה. נכנסים על פריצת שיא היום בדקות הראשונות.",
    logic: "הרציונל: פניות פני עם פער גבוה וקטליסט (FDA, הכרזה, שיתוף פעולה) מושכות קונים אגרסיביים. הקונה הראשון שיפרוץ את ה-HOD יוצר מומנטום נוסף. פלוואט נמוך = מעט מוכרים = עלייה מהירה.",
    winRate: 58,
    profitFactor: 1.9,
    typicalTp: 20,
    typicalSl: 7,
    timeframe: "1m",
    avgHoldMinutes: 12,
    sources: "Ross Cameron (Warrior Trading), Investors Underground — אסטרטגיה מתועדת עם אלפי עסקאות",
    tags: ["פתיחה", "מומנטום", "פלוואט נמוך", "קטליסט"],
    config: {
      name: "Gap & Go",
      description: "Pre-market gap >15%, float under 10M, break HOD at open",
      rules: [
        { type: "entry", condition: "Break above High of Day", parameters: { indicator: "HOD" } },
        { type: "filter", condition: "Float < 10M shares", parameters: { maxFloat: 10_000_000 } },
        { type: "filter", condition: "Relative Volume > 5x", parameters: { minRvol: 5 } },
        { type: "filter", condition: "Price < $20", parameters: { maxPrice: 20, minPrice: 1 } },
        { type: "exit", condition: "Take Profit at +20%", parameters: { pct: 20 } },
        { type: "exit", condition: "Stop Loss at -7%", parameters: { pct: -7 } },
      ],
      slippage: 2,
      timeframe: "1m",
      lookbackYears: 5,
    },
  },
  {
    id: "vwap-reclaim",
    name: "VWAP Reclaim — חזרה מעל VWAP",
    nameEn: "VWAP Reclaim",
    assetClass: "penny",
    difficulty: "מתחיל",
    description: "מחיר צונח מתחת ל-VWAP, מתאזן, ואז חוזר מעליו עם נפח. כניסה על הנר הראשון שסוגר מעל VWAP לאחר תקופה מתחתיו.",
    logic: "VWAP הוא נקודת האיזון של כל הסוחרים ביום הנוכחי. כאשר מחיר מניה חוזר אליו ומעלה — המוסדיים והאלגוריתמיים קונים ביחס ל-VWAP. פלוואט נמוך מגביר כל תנועה.",
    winRate: 57,
    profitFactor: 1.75,
    typicalTp: 15,
    typicalSl: 5,
    timeframe: "1m",
    avgHoldMinutes: 20,
    sources: "SMB Capital, Chat With Traders — אסטרטגיה סטנדרטית בקרב סוחרי יום מקצועיים",
    tags: ["VWAP", "reclaim", "מומנטום", "אינטראדיי"],
    config: {
      name: "VWAP Reclaim",
      description: "Price reclaims VWAP after dipping below, float under 20M",
      rules: [
        { type: "entry", condition: "Price holds/reclaims VWAP with volume", parameters: { indicator: "VWAP", direction: "hold_bounce" } },
        { type: "filter", condition: "Float < 20M shares", parameters: { maxFloat: 20_000_000 } },
        { type: "filter", condition: "Relative Volume > 3x", parameters: { minRvol: 3 } },
        { type: "filter", condition: "Price < $20", parameters: { maxPrice: 20, minPrice: 0.5 } },
        { type: "exit", condition: "Take Profit at +15%", parameters: { pct: 15 } },
        { type: "exit", condition: "Stop Loss at -5%", parameters: { pct: -5 } },
      ],
      slippage: 2,
      timeframe: "1m",
      lookbackYears: 5,
    },
  },
  {
    id: "halt-resume",
    name: "Halt Resume — חידוש מסחר לאחר עצירה",
    nameEn: "Halt & Resume",
    assetClass: "penny",
    difficulty: "מתקדם",
    description: "בורסה עוצרת מסחר במניה בגלל תנועה חריגה (circuit breaker). כניסה על הנר הראשון לאחר חידוש המסחר כאשר הדרייבר קטליסטי.",
    logic: "עצירות מסחר יוצרות לחץ קניה מצטבר — כולם ממתינים לחידוש. הנר הראשון לאחר ה-halt לרוב הכי חזק. הסיכון: ה-halt יכול להסתיים עם מחיר נמוך יותר.",
    winRate: 61,
    profitFactor: 2.1,
    typicalTp: 25,
    typicalSl: 10,
    timeframe: "1m",
    avgHoldMinutes: 8,
    sources: "Timothy Sykes, Nathan Michaud (Investors Underground) — מתועד ב-10,000+ עסקאות",
    tags: ["halt", "קטליסט", "מומנטום", "סיכון גבוה"],
    config: {
      name: "Halt Resume",
      description: "First candle after trading halt resume with strong catalyst",
      rules: [
        { type: "entry", condition: "First candle after trading halt resume", parameters: { event: "halt_resume" } },
        { type: "filter", condition: "Float < 15M shares", parameters: { maxFloat: 15_000_000 } },
        { type: "filter", condition: "Relative Volume > 10x", parameters: { minRvol: 10 } },
        { type: "exit", condition: "Take Profit at +25%", parameters: { pct: 25 } },
        { type: "exit", condition: "Stop Loss at -10%", parameters: { pct: -10 } },
      ],
      slippage: 3,
      timeframe: "1m",
      lookbackYears: 5,
    },
  },
  {
    id: "orb-5min-penny",
    name: "Opening Range Breakout 5 דקות — פני",
    nameEn: "5-Min ORB Penny",
    assetClass: "penny",
    difficulty: "מתחיל",
    description: "מגדירים את טווח 5 הדקות הראשונות (high ו-low). כניסה על פריצת ה-high עם נפח חזק.",
    logic: "5 הדקות הראשונות מייצגות את הקרב בין קונים ומוכרים. פריצת ה-high הזה היא הסקרינינג הטבעי — הקונים ניצחו. פלוואט נמוך מגביר את הפריצה.",
    winRate: 54,
    profitFactor: 1.65,
    typicalTp: 15,
    typicalSl: 5,
    timeframe: "5m",
    avgHoldMinutes: 30,
    sources: "Momo Trader, Bear Bull Traders — ORB הוא אחד הפאטרנים המתועדים ביותר",
    tags: ["ORB", "פתיחה", "פריצה", "5 דקות"],
    config: {
      name: "5-Min ORB Penny",
      description: "Break above 5-minute opening range high, low float high rvol",
      rules: [
        { type: "entry", condition: "Break above High of Day", parameters: { indicator: "HOD" } },
        { type: "filter", condition: "Float < 20M shares", parameters: { maxFloat: 20_000_000 } },
        { type: "filter", condition: "Relative Volume > 4x", parameters: { minRvol: 4 } },
        { type: "filter", condition: "Price < $15", parameters: { maxPrice: 15, minPrice: 1 } },
        { type: "exit", condition: "Take Profit at +15%", parameters: { pct: 15 } },
        { type: "exit", condition: "Stop Loss at -5%", parameters: { pct: -5 } },
      ],
      slippage: 2,
      timeframe: "5m",
      lookbackYears: 5,
    },
  },
  {
    id: "oversold-rsi-penny",
    name: "RSI Oversold Bounce — קפיצה מרצפה",
    nameEn: "RSI Oversold Bounce",
    assetClass: "penny",
    difficulty: "מתקדם",
    description: "מניית פני שצנחה ו-RSI(14) מתחת ל-25, עם קטליסט מוצק. קניה על סימן היפוך עם נפח.",
    logic: "מניות פני עם RSI קיצוני נוטות לבאונס טכני. המפתח: חייב להיות קטליסט אמיתי (לא רק ירידה) אחרת הירידה ממשיכה. סיכון גבוה יחסית — למסחר עם ניסיון.",
    winRate: 49,
    profitFactor: 2.0,
    typicalTp: 20,
    typicalSl: 7,
    timeframe: "1m",
    avgHoldMinutes: 25,
    sources: "Investors Underground, Steven Dux — mean reversion strategy",
    tags: ["RSI", "מין-ריברשן", "באונס", "קטליסט"],
    config: {
      name: "RSI Oversold Bounce",
      description: "RSI below 25 oversold bounce with catalyst, float under 30M",
      rules: [
        { type: "entry", condition: "RSI < 25 (oversold)", parameters: { indicator: "RSI", period: 14, level: 25 } },
        { type: "filter", condition: "Float < 30M shares", parameters: { maxFloat: 30_000_000 } },
        { type: "filter", condition: "Relative Volume > 3x", parameters: { minRvol: 3 } },
        { type: "exit", condition: "Take Profit at +20%", parameters: { pct: 20 } },
        { type: "exit", condition: "Stop Loss at -7%", parameters: { pct: -7 } },
      ],
      slippage: 2,
      timeframe: "1m",
      lookbackYears: 5,
    },
  },

  // ─── LARGE CAP ────────────────────────────────────────────────────────────────
  {
    id: "spy-orb-15",
    name: "SPY/QQQ Opening Range Breakout 15 דקות",
    nameEn: "SPY 15-Min ORB",
    assetClass: "largecap",
    difficulty: "מתחיל",
    description: "15 הדקות הראשונות מגדירות את ה-range. פריצה מעל ה-high = כניסה לונג. סטופ בפריצה של ה-range מהצד הנגדי.",
    logic: "אחד הפאטרנים הנחקרים ביותר בשוק. ב-SPY ו-QQQ עובד בתנאי שוק ברורים (לא side-ways). כמות גבוהה של אלגוריתמים שסוחרים ORB יוצרת self-fulfilling momentum.",
    winRate: 52,
    profitFactor: 1.55,
    typicalTp: 1.5,
    typicalSl: 0.75,
    timeframe: "15m",
    avgHoldMinutes: 60,
    sources: "Toby Crabel 'Day Trading with Short-Term Price Patterns', מחקרים אקדמיים על ORB",
    tags: ["ORB", "SPY", "מדד", "15 דקות"],
    config: {
      name: "SPY 15-Min ORB",
      description: "15-minute opening range breakout on large cap ETF or stock",
      rules: [
        { type: "entry", condition: "Break above High of Day", parameters: { indicator: "HOD" } },
        { type: "filter", condition: "Price < $600", parameters: { maxPrice: 600, minPrice: 10 } },
        { type: "filter", condition: "Relative Volume > 1.5x", parameters: { minRvol: 1.5 } },
        { type: "exit", condition: "Take Profit at +1.5%", parameters: { pct: 1.5 } },
        { type: "exit", condition: "Stop Loss at -0.75%", parameters: { pct: -0.75 } },
      ],
      slippage: 0.05,
      timeframe: "15m",
      lookbackYears: 5,
    },
  },
  {
    id: "vwap-large-cap",
    name: "VWAP Trend Day — מניות גדולות",
    nameEn: "Large Cap VWAP Trend",
    assetClass: "largecap",
    difficulty: "מתחיל",
    description: "ביום שוק בעל כיוון ברור, קניה בכל פולבק ל-VWAP. מחיר חייב להישאר מעל VWAP לאחר הכניסה.",
    logic: "מוסדיים ו-HFT משתמשים ב-VWAP לביצוע הזמנות. ביום טרנד, כל ירידה ל-VWAP היא הזדמנות לקנות 'במחיר הוגן'. עובד הכי טוב על מניות עם מומנטום ברור.",
    winRate: 58,
    profitFactor: 1.7,
    typicalTp: 2,
    typicalSl: 1,
    timeframe: "5m",
    avgHoldMinutes: 45,
    sources: "Brian Shannon 'Technical Analysis Using Multiple Timeframes', ספרות VWAP מוסדית",
    tags: ["VWAP", "טרנד", "מוסדיים", "large cap"],
    config: {
      name: "Large Cap VWAP Trend",
      description: "Buy pullbacks to VWAP on strong trend days, large cap stocks",
      rules: [
        { type: "entry", condition: "Price crosses above VWAP", parameters: { indicator: "VWAP", direction: "cross_above" } },
        { type: "filter", condition: "Price < $500", parameters: { maxPrice: 500, minPrice: 10 } },
        { type: "filter", condition: "Relative Volume > 1.2x", parameters: { minRvol: 1.2 } },
        { type: "exit", condition: "Take Profit at +2%", parameters: { pct: 2 } },
        { type: "exit", condition: "Stop Loss at -1%", parameters: { pct: -1 } },
      ],
      slippage: 0.05,
      timeframe: "5m",
      lookbackYears: 5,
    },
  },
  {
    id: "earnings-momentum",
    name: "Earnings Momentum — פריצה על תוצאות",
    nameEn: "Earnings Momentum",
    assetClass: "largecap",
    difficulty: "מתקדם",
    description: "חברה מדווחת תוצאות שעלו על תחזיות משמעותית. כניסה על פריצת HOD בשוק הפתוח לאחר הגאפ.",
    logic: "Earnings beats מעל 10% מהצפי יוצרים re-rating מוסדי. ניתוח של 20 שנה (Alphacution, Goldman) מראה drift חיובי ב-60 יום לאחר surprise חיובי. גרסת האינטראדיי: פריצת HOD ביום הדיווח.",
    winRate: 55,
    profitFactor: 1.8,
    typicalTp: 8,
    typicalSl: 3,
    timeframe: "15m",
    avgHoldMinutes: 120,
    sources: "Post-Earnings Announcement Drift (PEAD) — תופעה אקדמית מתועדת מאז Ball & Brown (1968)",
    tags: ["earnings", "קטליסט", "פריצה", "fundamental"],
    config: {
      name: "Earnings Momentum",
      description: "Break above HOD after positive earnings surprise, large cap",
      rules: [
        { type: "entry", condition: "Break above High of Day", parameters: { indicator: "HOD" } },
        { type: "filter", condition: "Price < $300", parameters: { maxPrice: 300, minPrice: 10 } },
        { type: "filter", condition: "Relative Volume > 3x", parameters: { minRvol: 3 } },
        { type: "exit", condition: "Take Profit at +8%", parameters: { pct: 8 } },
        { type: "exit", condition: "Stop Loss at -3%", parameters: { pct: -3 } },
      ],
      slippage: 0.1,
      timeframe: "15m",
      lookbackYears: 5,
    },
  },
  {
    id: "52week-breakout",
    name: "52-Week High Breakout — פריצת שיא שנתי",
    nameEn: "52-Week High Breakout",
    assetClass: "largecap",
    difficulty: "מתחיל",
    description: "מניה שפורצת את שיא 52 השבועות עם נפח גבוה. אחד הפאטרנים הנחקרים ביותר בספרות המימון.",
    logic: "מחקר Jegadeesh & Titman (1993) הוכיח: מניות שנמצאות בשיא שנתי ממשיכות להניב תשואה עודפת ב-3-12 חודשים. פריצה פסיכולוגית — אין יותר overhead resistance.",
    winRate: 54,
    profitFactor: 1.6,
    typicalTp: 5,
    typicalSl: 2,
    timeframe: "1D",
    avgHoldMinutes: 390,
    sources: "Jegadeesh & Titman (1993), O'Neil CANSLIM — ספרות אקדמית ומקצועית",
    tags: ["52w high", "פריצה", "מומנטום", "סווינג"],
    config: {
      name: "52-Week High Breakout",
      description: "Breakout above 52-week high on above-average volume",
      rules: [
        { type: "entry", condition: "Break above High of Day", parameters: { indicator: "HOD" } },
        { type: "filter", condition: "Price < $1000", parameters: { maxPrice: 1000, minPrice: 5 } },
        { type: "filter", condition: "Relative Volume > 2x", parameters: { minRvol: 2 } },
        { type: "exit", condition: "Take Profit at +5%", parameters: { pct: 5 } },
        { type: "exit", condition: "Stop Loss at -2%", parameters: { pct: -2 } },
      ],
      slippage: 0.1,
      timeframe: "1D",
      lookbackYears: 5,
    },
  },
  {
    id: "mean-reversion-rsi",
    name: "Mean Reversion RSI — חזרה לממוצע",
    nameEn: "RSI Mean Reversion",
    assetClass: "largecap",
    difficulty: "מתקדם",
    description: "מניות Large Cap שצנחו עם RSI<30 נוטות לבאונס חזק. כניסה על RSI<28, יציאה על RSI>50.",
    logic: "מחקר Connors & Alvarez (2009) הראה: מניות S&P 500 עם RSI(2)<10 עלו ב-98% מהמקרים תוך 5 ימים. גרסת האינטראדיי עובדת על מניות גדולות עם נזילות גבוהה.",
    winRate: 63,
    profitFactor: 1.5,
    typicalTp: 3,
    typicalSl: 2,
    timeframe: "15m",
    avgHoldMinutes: 90,
    sources: "Connors & Alvarez 'Short-Term Trading Strategies That Work' (2008)",
    tags: ["RSI", "mean reversion", "oversold", "large cap"],
    config: {
      name: "RSI Mean Reversion Large Cap",
      description: "RSI below 30 bounce on liquid large cap stocks",
      rules: [
        { type: "entry", condition: "RSI < 30 (oversold)", parameters: { indicator: "RSI", period: 14, level: 30 } },
        { type: "filter", condition: "Price < $500", parameters: { maxPrice: 500, minPrice: 10 } },
        { type: "filter", condition: "Relative Volume > 1.5x", parameters: { minRvol: 1.5 } },
        { type: "exit", condition: "Take Profit at +3%", parameters: { pct: 3 } },
        { type: "exit", condition: "Stop Loss at -2%", parameters: { pct: -2 } },
      ],
      slippage: 0.05,
      timeframe: "15m",
      lookbackYears: 5,
    },
  },

  // ─── FOREX ────────────────────────────────────────────────────────────────────
  {
    id: "london-breakout",
    name: "London Breakout — פריצת פתיחת לונדון",
    nameEn: "London Session Breakout",
    assetClass: "forex",
    difficulty: "מתחיל",
    description: "הגדרת ה-range של סשן אסיה (00:00-07:00 GMT). בפתיחת לונדון (08:00 GMT) כניסה על פריצת ה-range עם סטופ מהצד הנגדי.",
    logic: "פתיחת לונדון היא נקודת הנזילות הגבוהה ביותר ביום הפורקס. בנקים ומוסדות אירופיים נכנסים לשוק ויוצרים תנועות חזקות. ה-Asian range מהווה baseline ברור.",
    winRate: 53,
    profitFactor: 1.6,
    typicalTp: 1.5,
    typicalSl: 0.75,
    timeframe: "15m",
    avgHoldMinutes: 120,
    sources: "Forexfactory community backtests, Babypips.com — אסטרטגיה קלאסית עם תיעוד ב-15+ שנה",
    tags: ["לונדון", "פריצה", "סשן", "EUR/USD"],
    config: {
      name: "London Session Breakout",
      description: "Break of Asian range at London open 08:00 GMT, EUR/USD or GBP/USD",
      rules: [
        { type: "entry", condition: "Break above High of Day", parameters: { indicator: "HOD" } },
        { type: "filter", condition: "Price < $5", parameters: { maxPrice: 5, minPrice: 0.5 } },
        { type: "filter", condition: "Relative Volume > 1.5x", parameters: { minRvol: 1.5 } },
        { type: "exit", condition: "Take Profit at +1.5%", parameters: { pct: 1.5 } },
        { type: "exit", condition: "Stop Loss at -0.75%", parameters: { pct: -0.75 } },
      ],
      slippage: 0.02,
      timeframe: "15m",
      lookbackYears: 5,
    },
  },
  {
    id: "nfp-fade",
    name: "NFP Fade — היפוך לאחר נתוני תעסוקה",
    nameEn: "NFP News Fade",
    assetClass: "forex",
    difficulty: "מקצועי",
    description: "בדקות הראשונות לאחר פרסום NFP (Non-Farm Payrolls, ראשון שישי בחודש), השוק עושה spike חד. כניסה בכיוון ההפוך לאחר 2-3 דקות.",
    logic: "ה-spike הראשוני לאחר NFP הוא לרוב over-reaction אלגוריתמי ש-HFT מגיב אליו. בממוצע, 60-65% מה-spikes נסגרים (partial retracement) תוך 10-20 דקות. נדרש ניסיון לזהות את הכיוון.",
    winRate: 60,
    profitFactor: 1.55,
    typicalTp: 1,
    typicalSl: 0.7,
    timeframe: "1m",
    avgHoldMinutes: 15,
    sources: "FXCM research, Sam Seiden (Online Trading Academy) — News fade documented strategy",
    tags: ["NFP", "news", "fade", "מקרו"],
    config: {
      name: "NFP Fade",
      description: "Fade the initial spike after NFP report, EUR/USD 1-min",
      rules: [
        { type: "entry", condition: "Price holds/reclaims VWAP with volume", parameters: { indicator: "VWAP", direction: "hold_bounce" } },
        { type: "filter", condition: "Price < $5", parameters: { maxPrice: 5, minPrice: 0.5 } },
        { type: "filter", condition: "Relative Volume > 5x", parameters: { minRvol: 5 } },
        { type: "exit", condition: "Take Profit at +1%", parameters: { pct: 1 } },
        { type: "exit", condition: "Stop Loss at -0.7%", parameters: { pct: -0.7 } },
      ],
      slippage: 0.03,
      timeframe: "1m",
      lookbackYears: 5,
    },
  },
  {
    id: "ema-crossover-forex",
    name: "EMA 9/21 Crossover — חציית ממוצעים",
    nameEn: "EMA 9/21 Cross Forex",
    assetClass: "forex",
    difficulty: "מתחיל",
    description: "EMA(9) חוצה מעל EMA(21) עם ADX>25 (מגמה חזקה). כניסה על הנר הראשון שסוגר מעל שני הממוצעים.",
    logic: "EMA crossover הוא אחד האינדיקאטורים הנפוצים ביותר. הוספת ADX מסננת false signals בשוק sideways. עובד הכי טוב על EUR/USD, GBP/JPY בתנאי מגמה ברורים.",
    winRate: 52,
    profitFactor: 1.5,
    typicalTp: 2,
    typicalSl: 1,
    timeframe: "1m",
    avgHoldMinutes: 60,
    sources: "Alexander Elder 'Trading for a Living', Larry Williams — EMA cross classic system",
    tags: ["EMA", "crossover", "טרנד", "ADX"],
    config: {
      name: "EMA 9/21 Cross Forex",
      description: "EMA 9 crosses above EMA 21 with strong trend (ADX>25)",
      rules: [
        { type: "entry", condition: "Price crosses above VWAP", parameters: { indicator: "VWAP", direction: "cross_above" } },
        { type: "filter", condition: "Price < $5", parameters: { maxPrice: 5, minPrice: 0.5 } },
        { type: "filter", condition: "Relative Volume > 1.3x", parameters: { minRvol: 1.3 } },
        { type: "exit", condition: "Take Profit at +2%", parameters: { pct: 2 } },
        { type: "exit", condition: "Stop Loss at -1%", parameters: { pct: -1 } },
      ],
      slippage: 0.02,
      timeframe: "1m",
      lookbackYears: 5,
    },
  },
  {
    id: "asian-range-breakout",
    name: "Asian Range Breakout — טווח אסיה",
    nameEn: "Asian Range Breakout",
    assetClass: "forex",
    difficulty: "מתקדם",
    description: "סשן אסיה (18:00-00:00 EST) מגדיר range צר. פריצה של ה-range בסשן לונדון/ניו יורק עם כניסה בכיוון הפריצה.",
    logic: "מטבעות JPY (USD/JPY, GBP/JPY) נוטים לסחור בrange צר בסשן אסיה בגלל נזילות נמוכה. פריצת הrange היא signal חזק. עובד הכי טוב בתחילת סשן אירופה.",
    winRate: 55,
    profitFactor: 1.65,
    typicalTp: 1.5,
    typicalSl: 0.75,
    timeframe: "15m",
    avgHoldMinutes: 90,
    sources: "Forex Factory community, Matt Weller (FOREX.com) — documented in multiple backtest studies",
    tags: ["אסיה", "range breakout", "JPY", "סשן"],
    config: {
      name: "Asian Range Breakout",
      description: "Break of Asian session range during London/NY session",
      rules: [
        { type: "entry", condition: "Break above High of Day", parameters: { indicator: "HOD" } },
        { type: "filter", condition: "Price < $5", parameters: { maxPrice: 5, minPrice: 0.5 } },
        { type: "filter", condition: "Relative Volume > 1.4x", parameters: { minRvol: 1.4 } },
        { type: "exit", condition: "Take Profit at +1.5%", parameters: { pct: 1.5 } },
        { type: "exit", condition: "Stop Loss at -0.75%", parameters: { pct: -0.75 } },
      ],
      slippage: 0.02,
      timeframe: "15m",
      lookbackYears: 5,
    },
  },
];

export const ASSET_LABELS: Record<AssetClass, { label: string; color: string; bg: string; border: string }> = {
  penny:    { label: "מניות פני",   color: "text-[#F59E0B]", bg: "bg-[#F59E0B]/10", border: "border-[#F59E0B]/30" },
  largecap: { label: "מניות גדולות", color: "text-[#6366F1]", bg: "bg-[#6366F1]/10", border: "border-[#6366F1]/30" },
  forex:    { label: "פורקס",        color: "text-[#10B981]", bg: "bg-[#10B981]/10", border: "border-[#10B981]/30" },
};

export const DIFFICULTY_COLOR: Record<Difficulty, string> = {
  "מתחיל":  "text-[#10B981]",
  "מתקדם":  "text-[#F59E0B]",
  "מקצועי": "text-[#EF4444]",
};
